colorScheme = "blowfish"
defaultAppearance = "dark"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true
replyByEmail = false
mainSections = [ "posts",]
disableImageOptimization = false
disableTextInHeader = false
giteaDefaultServer = "https://git.fsfe.org"
forgejoDefaultServer = "https://v8.next.forgejo.org"

# defaultBackgroundImage = "img/background_blur.jpg"

[header]
layout = "basic"

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "page"
showRecent = true
showRecentItems = 6
showMoreLink = true
showMoreLinkDest = "/posts/"
cardView = true
cardViewScreenWidth = false
layoutBackgroundBlur = true
homepageImage = "img/background_blur.jpg"

[article]
showDate = true
showViews = true
showLikes = true
showDateOnlyInArticle = false
showDateUpdated = false
showAuthor = false
showHero = true
heroStyle = "background"
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = false
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = false
showTableOfContents = true
showTaxonomies = true
showAuthorsBadges = false
showWordCount = false
showZenMode = false
showRelatedContent = true
relatedContentLimit = 3

[list]
showHero = false
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = false
showSummary = false
showViews = false
showLikes = false
showTableOfContents = false
showCards = false
orderByWeight = false
groupByYear = true
cardView = false
cardViewScreenWidth = false
constrainItemsWidth = false

[sitemap]
excludedKinds = [ "taxonomy", "term" ]

[taxonomy]
showTermCount = true
showHero = ""
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = false
cardView = false

[term]
showHero = false
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
groupByYear = false
cardView = false
cardViewScreenWidth = false

[firebase]
apiKey = "AIzaSyAfO4iBFVOYdNuEFyHTt-1viaG0HvVI5eo"
authDomain = "qqq-investor.firebaseapp.com"
projectId = "qqq-investor"
storageBucket = "qqq-investor.appspot.com"
messagingSenderId = "144896880465"
appId = "1:144896880465:web:64989e17b6b1ed9a986d70"
measurementId = "G-C0WXZ17FTN"

[fathomAnalytics]

[umamiAnalytics]

[selineAnalytics]

[buymeacoffee]
#  identifier = "jomonylw"
#  globalWidget = true
#  globalWidgetMessage = ""
#  globalWidgetColor = "#FFDD00"
#  globalWidgetPosition = "Right"

[verification]
